import type { BenchmarkId, BenchmarkMetricIdForUnit, BenchmarkUnit } from "@litellm-bench/catalog";
import type { TopLevelSpec } from "vega-lite";
import { chartPresentation, readChartTheme } from "../styles/charts.ts";
import { annotationLayers, type BenchmarkAnnotation, resolveAnnotations } from "./annotations.ts";
import type { BenchmarkRecord } from "./data.ts";
import { unique, withBase } from "./data.ts";
import { observations } from "./observations.ts";
import { uniqueVersions } from "./versions.ts";

export interface DetailChartDefinition {
  description: string;
  metricIds: readonly string[];
  title: string;
  unit: string;
}

type ContractDetailChartDefinition<I extends BenchmarkId> = {
  [U in BenchmarkUnit<I>]:
    & Omit<DetailChartDefinition, "metricIds" | "unit">
    & {
      metricIds: readonly BenchmarkMetricIdForUnit<I, U>[];
      unit: U;
    };
}[BenchmarkUnit<I>];

type DetailChartRegistry = {
  [I in BenchmarkId]?: readonly ContractDetailChartDefinition<I>[];
};

const detailCharts = {
  "proxy-ocr": [
    {
      title: "1 MiB throughput",
      description: "Median successful requests per second by implementation",
      unit: "RPS",
      metricIds: ["core_1m.python.rps", "core_1m.rust.rps"],
    },
    {
      title: "1 MiB paired improvement",
      description: "Median Rust throughput divided by paired Python throughput",
      unit: "x",
      metricIds: ["core_1m.paired_ratio"],
    },
    {
      title: "8 MiB throughput",
      description: "Median successful requests per second by implementation",
      unit: "RPS",
      metricIds: ["core_8m.python.rps", "core_8m.rust.rps"],
    },
    {
      title: "8 MiB paired improvement",
      description: "Median Rust throughput divided by paired Python throughput",
      unit: "x",
      metricIds: ["core_8m.paired_ratio"],
    },
    {
      title: "1 MiB p95 latency",
      description: "Median p95 successful response latency by implementation",
      unit: "ms",
      metricIds: ["core_1m.python.latency_p95_ms", "core_1m.rust.latency_p95_ms"],
    },
    {
      title: "1 MiB CPU usage",
      description: "Median average container CPU by implementation",
      unit: "%",
      metricIds: ["core_1m.python.cpu_average_percent", "core_1m.rust.cpu_average_percent"],
    },
    {
      title: "1 MiB peak memory",
      description: "Median peak container memory by implementation",
      unit: "MiB",
      metricIds: ["core_1m.python.peak_memory_mib", "core_1m.rust.peak_memory_mib"],
    },
    {
      title: "1 MiB idle memory",
      description: "Median post-load anonymous memory by implementation",
      unit: "MiB",
      metricIds: ["core_1m.python.idle_anon_mib", "core_1m.rust.idle_anon_mib"],
    },
    {
      title: "8 MiB p95 latency",
      description: "Median p95 successful response latency by implementation",
      unit: "ms",
      metricIds: ["core_8m.python.latency_p95_ms", "core_8m.rust.latency_p95_ms"],
    },
    {
      title: "8 MiB CPU usage",
      description: "Median average container CPU by implementation",
      unit: "%",
      metricIds: ["core_8m.python.cpu_average_percent", "core_8m.rust.cpu_average_percent"],
    },
    {
      title: "8 MiB peak memory",
      description: "Median peak container memory by implementation",
      unit: "MiB",
      metricIds: ["core_8m.python.peak_memory_mib", "core_8m.rust.peak_memory_mib"],
    },
    {
      title: "8 MiB idle memory",
      description: "Median post-load anonymous memory by implementation",
      unit: "MiB",
      metricIds: ["core_8m.python.idle_anon_mib", "core_8m.rust.idle_anon_mib"],
    },
  ],
  "sdk-import-time": [
    {
      title: "Import-time distribution",
      description: "Fresh-process timing statistics retained by each run",
      unit: "ms",
      metricIds: [
        "import.minimum",
        "import.median",
        "import.p95",
        "import.maximum",
        "import.first",
      ],
    },
  ],
  "sdk-import-footprint": [
    {
      title: "Import footprint",
      description: "Peak resident memory and files generated by first import",
      unit: "MiB",
      metricIds: ["import.peak_rss", "import.disk_growth"],
    },
    {
      title: "Loaded modules",
      description: "New modules loaded by the root import",
      unit: "modules",
      metricIds: ["import.loaded_modules"],
    },
  ],
  "sdk-package-size": [
    {
      title: "Package size",
      description: "Wheel, resolved download closure, and installed environment",
      unit: "MiB",
      metricIds: ["package.wheel", "package.download", "package.installed"],
    },
    {
      title: "Resolved artifacts",
      description: "Artifact count in the dependency closure",
      unit: "artifacts",
      metricIds: ["package.artifacts"],
    },
  ],
} satisfies DetailChartRegistry;

function hasCustomDetailCharts(benchmarkId: string): benchmarkId is keyof typeof detailCharts {
  return Object.hasOwn(detailCharts, benchmarkId);
}

type ChartTheme = ReturnType<typeof readChartTheme>;

export function overviewSpec(
  records: BenchmarkRecord[],
  theme: ChartTheme = readChartTheme(),
  annotations: readonly BenchmarkAnnotation[] = [],
  base = "",
): TopLevelSpec | null {
  const values = observations(records);
  if (!values.length) return null;
  const names = unique(values.map((item) => item.name));
  return {
    $schema: "https://vega.github.io/schema/vega-lite/v6.json",
    background: theme.colors.surface,
    config: theme.config,
    spacing: chartPresentation.spacing,
    vconcat: names.map((name) => {
      const metrics = values.filter((item) => item.name === name);
      const metric = metrics[0];
      return {
        width: "container",
        height: chartPresentation.overviewHeight,
        title: {
          text: name,
          subtitle: `${metric.label} · ${unique(metrics.map((item) => item.unit)).join(" / ")}`,
        },
        data: {
          values: metrics.map((item) => ({
            ...item,
            path: withBase(`${item.benchmarkId}/`, base),
          })),
        },
        encoding: {
          x: {
            field: "version",
            type: "ordinal",
            sort: [...uniqueVersions(values.map((item) => item.version))],
            scale: { type: "band", paddingInner: 0, paddingOuter: 0.5 },
            title: "LiteLLM version",
          },
          detail: { field: "key", type: "nominal" },
          color: {
            field: "environment",
            type: "nominal",
            title: "Configuration",
            scale: { range: theme.series },
            legend: null,
          },
        },
        layer: [
          {
            mark: { type: "line", strokeWidth: chartPresentation.lineWidth },
            encoding: {
              y: {
                aggregate: "median",
                field: "value",
                type: "quantitative",
                title: metric.unit,
                scale: { zero: false, nice: true },
              },
            },
          },
          {
            mark: {
              type: "point",
              cursor: "pointer",
              filled: true,
              size: chartPresentation.pointSize,
            },
            encoding: {
              y: {
                field: "value",
                type: "quantitative",
                title: metric.unit,
                scale: { zero: false, nice: true },
              },
              href: { field: "path" },
              tooltip: [
                { field: "name", title: "Metric" },
                { field: "version", title: "Version" },
                { field: "value", type: "quantitative", title: "Value", format: ".3~r" },
                { field: "unit", title: "Unit" },
                { field: "environment", title: "Configuration" },
              ],
            },
          },
          ...annotationLayers(
            resolveAnnotations(
              records.filter((record) => record.benchmark_id === metric.benchmarkId),
              [metric.metricId],
              annotations,
            ),
            theme.colors.foreground,
          ),
        ],
      };
    }),
  };
}

export function detailDefinitions(
  benchmarkId: string,
  records: BenchmarkRecord[],
): readonly DetailChartDefinition[] {
  const custom: readonly DetailChartDefinition[] = hasCustomDetailCharts(benchmarkId)
    ? detailCharts[benchmarkId]
    : [];
  const metrics = observations(records.filter((record) => record.benchmark_id === benchmarkId));
  const uncovered = metrics.filter((metric) =>
    !custom.some((chart) => chart.unit === metric.unit && chart.metricIds.includes(metric.metricId))
  );
  const keys = unique(uncovered.map((metric) => JSON.stringify([metric.metricId, metric.unit])));
  return [
    ...custom,
    ...keys.map((key) => {
      const metric = uncovered.find((item) => JSON.stringify([item.metricId, item.unit]) === key)!;
      return {
        title: metric.name,
        description: metric.label,
        unit: metric.unit,
        metricIds: [metric.metricId],
      };
    }),
  ];
}

export function detailSpec(
  benchmarkId: string,
  records: BenchmarkRecord[],
  definition: DetailChartDefinition,
  theme: ChartTheme = readChartTheme(),
  annotations: readonly BenchmarkAnnotation[] = [],
): TopLevelSpec | null {
  const scoped = records.filter((record) => record.benchmark_id === benchmarkId);
  const values = observations(scoped)
    .filter((metric) =>
      definition.metricIds.includes(metric.metricId) && metric.unit === definition.unit
    )
    .map((metric) => ({
      ...metric,
      series: `${metric.label}${metric.group ? ` · ${metric.group}` : ""}`,
    }));
  if (!values.length) return null;
  return {
    $schema: "https://vega.github.io/schema/vega-lite/v6.json",
    width: "container",
    height: chartPresentation.detailHeight,
    data: { values },
    config: theme.config,
    encoding: {
      x: {
        field: "version",
        type: "ordinal",
        sort: [...uniqueVersions(values.map((item) => item.version))],
        scale: { type: "band", paddingInner: 0, paddingOuter: 0.5 },
        title: "LiteLLM version",
      },
      detail: { field: "key", type: "nominal" },
      color: {
        field: "series",
        type: "nominal",
        title: null,
        scale: { range: theme.series },
        legend: { orient: "bottom", direction: "horizontal", symbolType: "stroke" },
      },
    },
    layer: [
      {
        mark: { type: "line", strokeWidth: chartPresentation.lineWidth },
        encoding: {
          strokeDash: { field: "environment", type: "nominal", legend: null },
          y: {
            aggregate: "median",
            field: "value",
            type: "quantitative",
            title: definition.unit,
            scale: { zero: false, nice: true },
          },
        },
      },
      {
        mark: { type: "point", filled: true, size: chartPresentation.pointSize },
        encoding: {
          y: {
            field: "value",
            type: "quantitative",
            title: definition.unit,
            scale: { zero: false, nice: true },
          },
          tooltip: [
            { field: "name", title: "Metric" },
            { field: "version", title: "Version" },
            { field: "value", type: "quantitative", title: "Value", format: ".3~r" },
            { field: "environment", title: "Configuration" },
          ],
        },
      },
      ...annotationLayers(
        resolveAnnotations(scoped, definition.metricIds, annotations),
        theme.colors.foreground,
      ),
    ],
  };
}
